CREATE DATABASE IF NOT EXISTS myhub;

-- 用户表

CREATE TABLE
    IF NOT EXISTS `users`(
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(30) NOT NULL UNIQUE,
        password VARCHAR(50) NOT NULL,
        createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- 动态表

CREATE TABLE
    IF NOT EXISTS `moment` (
        id INT PRIMARY KEY AUTO_INCREMENT,
        content VARCHAR(1000) NOT NULL,
        user_id INT NOT NULL,
        createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        Foreign Key (user_id) REFERENCES `users`(id) ON DELETE CASCADE ON UPDATE CASCADE
    );